name: SGB API - Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          NODE_ENV: test
          API_KEY_SECRET: chave_super_secreta_32_bytes
          MULTA_DIARIA: "2.00"
          MULTA_MAXIMA: "50.00"
          PRAZO_ALUNO: "7"
          PRAZO_PROFESSOR: "14"
          LIMITE_ALUNO: "3"
          LIMITE_PROFESSOR: "5"
        run: npm test
